package dev.vmd1.gossip.features.screenmirror

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertThrows
import org.junit.Test
import java.io.File

/** The Kotlin side of the shared vectors (`schema/screen-cipher-vectors.json`, generated by Swift). */
class ScreenCipherTest {
    private fun hex(s: String) = ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }

    private fun vectors(): JsonObject {
        var dir: File? = File("").absoluteFile
        while (dir != null && !File(dir, "schema/screen-cipher-vectors.json").exists()) dir = dir.parentFile
        return Json.parseToJsonElement(File(checkNotNull(dir), "schema/screen-cipher-vectors.json").readText()).jsonObject
    }

    @Test
    fun `shared vectors match`() {
        val root = vectors()
        val secret = hex(root["secretHex"]!!.jsonPrimitive.content)
        val sessionId = root["sessionId"]!!.jsonPrimitive.content
        for (c in root["cases"]!!.jsonArray) {
            val o = c.jsonObject
            val viewerSends = o["viewerSends"]!!.jsonPrimitive.boolean
            val plaintext = hex(o["plaintextHex"]!!.jsonPrimitive.content)
            val sealed = hex(o["sealedHex"]!!.jsonPrimitive.content)
            val counter = o["counter"]!!.jsonPrimitive.long
            // deviceSide = !viewerSends is the *receiving* end for this vector
            assertArrayEquals(plaintext, ScreenCipher(secret, sessionId, deviceSide = viewerSends).open(sealed))
            assertArrayEquals(sealed, ScreenCipher(secret, sessionId, deviceSide = !viewerSends).seal(plaintext, counter))
        }
    }

    @Test
    fun `rejects replay forgery wrong session and reflection`() {
        val secret = ByteArray(32) { 9 }
        val viewer = ScreenCipher(secret, "s1", deviceSide = false)
        val device = ScreenCipher(secret, "s1", deviceSide = true)
        val m1 = viewer.seal("one".toByteArray())
        val m2 = viewer.seal("two".toByteArray())
        assertArrayEquals("one".toByteArray(), device.open(m1))
        assertThrows(ScreenCipher.Failure::class.java) { device.open(m1) }
        assertArrayEquals("two".toByteArray(), device.open(m2))

        val forged = viewer.seal("three".toByteArray()).also { it[it.size - 1] = (it[it.size - 1].toInt() xor 1).toByte() }
        assertThrows(ScreenCipher.Failure::class.java) { device.open(forged) }
        assertThrows(ScreenCipher.Failure::class.java) { ScreenCipher(secret, "other", true).open(viewer.seal("x".toByteArray())) }
        assertThrows(ScreenCipher.Failure::class.java) { ScreenCipher(secret, "s1", deviceSide = false).open(viewer.seal("y".toByteArray())) }
    }
}
