package dev.vmd1.gossip.features.universalcontrol

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.boolean
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/** The Kotlin side of the shared wire-format vectors (`schema/control-test-vectors.json`, generated by Swift). */
class ControlProtocolTest {
    private fun hex(s: String) = ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }

    private fun vectors(): JsonObject {
        var dir: File? = File("").absoluteFile
        while (dir != null && !File(dir, "schema/control-test-vectors.json").exists()) dir = dir.parentFile
        return Json.parseToJsonElement(File(checkNotNull(dir) { "schema/control-test-vectors.json not found" }, "schema/control-test-vectors.json").readText()).jsonObject
    }

    private fun frameFor(f: JsonObject): ControlFrame {
        fun i(k: String) = f[k]!!.jsonPrimitive.int
        return when (val t = f["type"]!!.jsonPrimitive.content) {
            "hello" -> ControlFrame.Hello(f["sessionId"]!!.jsonPrimitive.content)
            "hello_ack" -> ControlFrame.HelloAck(ControlDisplayInfo(i("width"), i("height"), i("rotation"), i("backend")))
            "display_info" -> ControlFrame.DisplayInfo(ControlDisplayInfo(i("width"), i("height"), i("rotation"), i("backend")))
            "enter" -> ControlFrame.Enter(ControlEdge.from(i("edge"))!!, i("position"))
            "leave" -> ControlFrame.Leave
            "mouse_move" -> ControlFrame.MouseMove(i("dx"), i("dy"))
            "buttons" -> ControlFrame.Buttons(i("mask"))
            "scroll" -> ControlFrame.Scroll(i("dx"), i("dy"))
            "key" -> ControlFrame.Key(i("usage"), f["down"]!!.jsonPrimitive.boolean, i("modifiers"))
            "text" -> ControlFrame.Text(f["text"]!!.jsonPrimitive.content)
            "ping" -> ControlFrame.Ping
            "pong" -> ControlFrame.Pong
            "error" -> ControlFrame.Error(f["reason"]!!.jsonPrimitive.content)
            else -> fail("unknown vector frame type $t").let { throw IllegalStateException() }
        }
    }

    @Test fun everySharedVectorEncodesDecodesAndSealsIdentically() {
        val v = vectors()
        val secret = hex(v["secretHex"]!!.jsonPrimitive.content)
        val sessionId = v["sessionId"]!!.jsonPrimitive.content
        val deviceSide = ControlCipher(secret, sessionId, deviceSide = true)
        val macSide = ControlCipher(secret, sessionId, deviceSide = false)
        val cases = v["cases"]!!.jsonArray
        assertTrue(cases.size >= 13)
        for (c in cases) {
            val o = c.jsonObject
            val name = o["name"]!!.jsonPrimitive.content
            val m2d = o["direction"]!!.jsonPrimitive.content == "m2d"
            val frame = frameFor(o["frame"]!!.jsonObject)
            val plaintext = hex(o["plaintextHex"]!!.jsonPrimitive.content)
            val sealed = hex(o["sealedHex"]!!.jsonPrimitive.content)
            assertArrayEquals("$name plaintext", plaintext, frame.encode())
            assertEquals("$name decode", frame, ControlFrame.decode(plaintext))
            val sender = if (m2d) macSide else deviceSide
            assertArrayEquals("$name sealed", sealed, sender.seal(plaintext, o["counter"]!!.jsonPrimitive.content.toLong()))
        }
        // And the receiving side opens what the sending side sealed, in counter order.
        val rx = ControlCipher(secret, sessionId, deviceSide = true)
        for (c in cases.map { it.jsonObject }.filter { it["direction"]!!.jsonPrimitive.content == "m2d" }) {
            assertEquals(frameFor(c["frame"]!!.jsonObject), rx.open(hex(c["sealedHex"]!!.jsonPrimitive.content)))
        }
    }

    @Test fun replayTamperingAndWrongKeysAreRejected() {
        val secret = ByteArray(32) { it.toByte() }
        val mac = ControlCipher(secret, "s", deviceSide = false)
        val dev = ControlCipher(secret, "s", deviceSide = true)
        val one = mac.seal(ControlFrame.Ping)
        assertEquals(ControlFrame.Ping, dev.open(one))
        try { dev.open(one); fail() } catch (e: ControlCipher.Failure) { assertTrue(e.replayed) }
        val two = mac.seal(ControlFrame.Leave)
        val bad = two.copyOf().also { it[it.size - 1] = (it[it.size - 1].toInt() xor 1).toByte() }
        try { dev.open(bad); fail() } catch (e: ControlCipher.Failure) { assertEquals("authentication", e.message) }
        assertEquals(ControlFrame.Leave, dev.open(two)) // a forged frame doesn't burn the counter
        val other = ControlCipher(ByteArray(32) { 9 }, "s", deviceSide = true)
        try { other.open(mac.seal(ControlFrame.Ping)); fail() } catch (e: ControlCipher.Failure) { assertEquals("authentication", e.message) }
        val otherSession = ControlCipher(secret, "t", deviceSide = true)
        try { otherSession.open(mac.seal(ControlFrame.Ping)); fail() } catch (e: ControlCipher.Failure) { assertEquals("authentication", e.message) }
        try { dev.open(ByteArray(10)); fail() } catch (e: ControlCipher.Failure) { assertEquals("bad length", e.message) }
    }

    @Test fun malformedFramesDecodeToNull() {
        assertNull(ControlFrame.decode(byteArrayOf()))
        assertNull(ControlFrame.decode(byteArrayOf(0x7f)))
        assertNull(ControlFrame.decode(byteArrayOf(0x12, 0, 1)))        // truncated mouse move
        assertNull(ControlFrame.decode(byteArrayOf(0x15, 0, 4, 2, 0)))  // key "down" must be 0 or 1
        assertNull(ControlFrame.decode(byteArrayOf(0x10, 9, 0, 0)))     // unknown edge
    }

    private fun hex(b: ByteArray) = b.joinToString("") { "%02x".format(it) }

    @Test fun cursorFramesHaveTheAgreedBytes() {
        // The same bytes are asserted in ControlProtocolTests.swift.
        assertEquals("1809", hex(ControlFrame.CursorQuery(9).encode()))
        assertEquals("86070102030405060708", hex(ControlFrame.CursorPos(7, 0x0102, 0x0304, 0x05060708L).encode()))
        for (f in listOf(ControlFrame.CursorQuery(255), ControlFrame.CursorPos(7, 65535, 0, 4_000_000_000L))) {
            assertEquals(f, ControlFrame.decode(f.encode()))
        }
        assertNull(ControlFrame.decode(byteArrayOf(0x86.toByte(), 1, 0, 0, 0, 0, 0, 0))) // truncated
        assertNull(ControlFrame.decode(byteArrayOf(0x18)))
    }
}
