//! Clipboard sync (`clipboard.update`): the content policy and the loop guard. Reading and writing the actual
//! pasteboard belongs to the shell.
//!
//! Loop suppression: writing the clipboard ourselves in response to a remote update looks exactly like a local
//! copy to the next poll. The guard remembers the last value this device wrote (received from a peer) and the last
//! value it sent, and refuses to send a value that matches either, so neither an echo nor the periodic resync can
//! ping-pong. The resync (`clipboard.update` every 60s) goes through the same guard, so it is a no-op when nothing
//! changed.

use base64::{engine::general_purpose::STANDARD as B64, Engine};
use serde_json::{Map, Value};
use sha2::{Digest, Sha256};

use super::{object, Outgoing};

pub const MAX_TEXT_BYTES: usize = 1 << 20;
pub const MAX_IMAGE_BYTES: usize = 8 << 20;
pub const MAX_IMAGE_PIXELS: u64 = 40_000_000;

/// Pasteboard types that mark content that must not be stored or synced (concealed, transient, auto-generated,
/// and 1Password's own marker), per the nspasteboard.org convention.
pub const SENSITIVE_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
];

pub fn is_sensitive<S: AsRef<str>>(types: &[S]) -> bool {
    types.iter().any(|t| SENSITIVE_TYPES.contains(&t.as_ref()))
}

pub fn text_allowed(text: &str) -> bool {
    text.len() <= MAX_TEXT_BYTES
}

pub fn image_bytes_allowed(len: usize) -> bool {
    len > 0 && len <= MAX_IMAGE_BYTES
}

/// Width and height from a PNG's IHDR chunk, without decoding the image.
pub fn png_dimensions(data: &[u8]) -> Option<(u32, u32)> {
    const SIGNATURE: &[u8] = &[0x89, b'P', b'N', b'G', 0x0d, 0x0a, 0x1a, 0x0a];
    if data.len() < 24 || &data[..8] != SIGNATURE || &data[12..16] != b"IHDR" {
        return None;
    }
    let w = u32::from_be_bytes(data[16..20].try_into().ok()?);
    let h = u32::from_be_bytes(data[20..24].try_into().ok()?);
    (w > 0 && h > 0).then_some((w, h))
}

/// Refuses data that is not a PNG or whose decoded size is a decompression bomb.
pub fn is_reasonable_png(data: &[u8]) -> bool {
    png_dimensions(data).is_some_and(|(w, h)| u64::from(w) * u64::from(h) <= MAX_IMAGE_PIXELS)
}

fn digest(data: &[u8]) -> [u8; 32] {
    Sha256::digest(data).into()
}

#[derive(Debug, Clone, Default)]
pub struct ClipboardGuard {
    last_remote_text: Option<String>,
    last_sent_text: Option<String>,
    last_remote_image: Option<[u8; 32]>,
    last_sent_image: Option<[u8; 32]>,
}

impl ClipboardGuard {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn text_payload(me: &str, text: &str) -> Map<String, Value> {
        object([
            ("kind", "text".into()),
            ("text", text.into()),
            ("sourceDeviceId", me.into()),
        ])
    }

    pub fn image_payload(me: &str, byte_len: usize) -> Map<String, Value> {
        object([
            ("kind", "image".into()),
            ("sourceDeviceId", me.into()),
            ("contentType", "image/png".into()),
            ("byteLength", (byte_len as u64).into()),
        ])
    }

    /// Whether a freshly observed local text value should be sent; records it as sent when it should.
    pub fn outgoing_text(&mut self, me: &str, text: &str, sensitive: bool) -> Option<Outgoing> {
        if sensitive || !text_allowed(text) {
            return None;
        }
        if self.last_remote_text.as_deref() == Some(text)
            || self.last_sent_text.as_deref() == Some(text)
        {
            return None;
        }
        self.last_sent_text = Some(text.to_owned());
        Some(Outgoing::broadcast(
            "clipboard.update",
            Self::text_payload(me, text),
        ))
    }

    /// Same for an image already normalised to PNG. The shell then sends the envelope with `png` as its raw frame.
    pub fn outgoing_image(&mut self, me: &str, png: &[u8], sensitive: bool) -> Option<Outgoing> {
        if sensitive || !image_bytes_allowed(png.len()) {
            return None;
        }
        let d = digest(png);
        if self.last_remote_image == Some(d) || self.last_sent_image == Some(d) {
            return None;
        }
        self.last_sent_image = Some(d);
        Some(Outgoing::broadcast(
            "clipboard.update",
            Self::image_payload(me, png.len()),
        ))
    }

    /// An incoming text update; returns the text to write to the local clipboard, or `None` if it is refused.
    pub fn incoming_text(&mut self, payload: &Map<String, Value>) -> Option<String> {
        let text = payload.get("text")?.as_str()?;
        if !text_allowed(text) {
            return None;
        }
        self.last_remote_text = Some(text.to_owned());
        Some(text.to_owned())
    }

    /// An incoming image update (its raw frame); true if it should be written to the local clipboard.
    pub fn incoming_image(&mut self, payload: &Map<String, Value>, png: &[u8]) -> bool {
        if payload.get("kind").and_then(Value::as_str) != Some("image")
            || !image_bytes_allowed(png.len())
            || !is_reasonable_png(png)
        {
            return false;
        }
        self.last_remote_image = Some(digest(png));
        true
    }

    /// Base64 helper for shells that carry the image inline instead of as a raw frame.
    pub fn encode_inline(png: &[u8]) -> String {
        B64.encode(png)
    }
}
