//! `Noise_IK_25519_ChaChaPoly_SHA256` exactly as the Mac (CryptoKit) and Android (javax.crypto) apps run it.
//!
//! This is standard Noise: the IETF ChaCha20-Poly1305 AEAD with a nonce of four zero bytes plus the little-endian
//! 64-bit counter, HMAC-SHA256 HKDF with the two-output form, an empty prologue, and the responder's static key
//! as the `<- s` pre-message. Nothing here is custom, which is what the vectors in `schema/noise-ik-vectors.json`
//! (generated by an independent implementation) pin down.
//!
//! The handshake is an explicit state machine that never touches the network or an RNG: callers pass in the
//! ephemeral secret and move bytes themselves. Keys are zeroized on drop.

use chacha20poly1305::{aead::Aead, aead::Payload, ChaCha20Poly1305, Key, KeyInit, Nonce};
use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};
use thiserror::Error;
use x25519_dalek::{PublicKey, StaticSecret};
use zeroize::{Zeroize, ZeroizeOnDrop};

pub const PROTOCOL_NAME: &str = "Noise_IK_25519_ChaChaPoly_SHA256";
pub const DH_LEN: usize = 32;
pub const TAG_LEN: usize = 16;
/// Length of the encrypted static key inside message 1.
pub const ENCRYPTED_STATIC_LEN: usize = DH_LEN + TAG_LEN;

#[derive(Debug, Error, PartialEq, Eq, Clone, Copy)]
pub enum NoiseError {
    #[error("malformed Noise handshake message")]
    InvalidMessage,
    #[error("Noise AEAD authentication failed")]
    Decryption,
    #[error("a Diffie-Hellman result was a low-order point")]
    WeakKey,
    #[error("handshake method called out of order or for the wrong role")]
    WrongState,
    #[error("the cipher nonce space is exhausted")]
    NonceExhausted,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Role {
    Initiator,
    Responder,
}

/// A long-term X25519 identity key pair.
#[derive(ZeroizeOnDrop)]
pub struct StaticKeypair {
    secret: StaticSecret,
    #[zeroize(skip)]
    public: PublicKey,
}

impl StaticKeypair {
    pub fn from_secret_bytes(bytes: [u8; 32]) -> Self {
        let secret = StaticSecret::from(bytes);
        let public = PublicKey::from(&secret);
        Self { secret, public }
    }

    pub fn public_bytes(&self) -> [u8; 32] {
        self.public.to_bytes()
    }

    pub fn secret_bytes(&self) -> [u8; 32] {
        self.secret.to_bytes()
    }
}

impl Clone for StaticKeypair {
    fn clone(&self) -> Self {
        Self::from_secret_bytes(self.secret.to_bytes())
    }
}

impl std::fmt::Debug for StaticKeypair {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("StaticKeypair")
            .field("public", &self.public.as_bytes())
            .finish_non_exhaustive()
    }
}

fn dh(secret: &StaticSecret, public: &[u8; 32]) -> Result<[u8; 32], NoiseError> {
    let shared = secret.diffie_hellman(&PublicKey::from(*public));
    if !shared.was_contributory() {
        return Err(NoiseError::WeakKey);
    }
    Ok(shared.to_bytes())
}

fn sha256(parts: &[&[u8]]) -> [u8; 32] {
    let mut h = Sha256::new();
    for p in parts {
        h.update(p);
    }
    h.finalize().into()
}

fn hmac(key: &[u8], data: &[u8]) -> [u8; 32] {
    let mut mac = <Hmac<Sha256> as Mac>::new_from_slice(key).expect("HMAC accepts any key length");
    mac.update(data);
    mac.finalize().into_bytes().into()
}

/// Noise HKDF with two outputs (spec section 4.3).
fn hkdf2(chaining_key: &[u8; 32], ikm: &[u8]) -> ([u8; 32], [u8; 32]) {
    let temp = hmac(chaining_key, ikm);
    let out1 = hmac(&temp, &[0x01]);
    let mut second = out1.to_vec();
    second.push(0x02);
    let out2 = hmac(&temp, &second);
    (out1, out2)
}

fn nonce_bytes(n: u64) -> [u8; 12] {
    let mut out = [0u8; 12];
    out[4..].copy_from_slice(&n.to_le_bytes());
    out
}

/// AEAD cipher state: a key and a strictly increasing nonce (spec section 5.1).
#[derive(Zeroize, ZeroizeOnDrop)]
struct CipherState {
    key: Option<[u8; 32]>,
    #[zeroize(skip)]
    n: u64,
}

impl CipherState {
    fn empty() -> Self {
        Self { key: None, n: 0 }
    }

    fn with_key(key: [u8; 32]) -> Self {
        Self {
            key: Some(key),
            n: 0,
        }
    }

    fn set_key(&mut self, key: [u8; 32]) {
        self.key = Some(key);
        self.n = 0;
    }

    fn encrypt_with_ad(&mut self, ad: &[u8], plaintext: &[u8]) -> Result<Vec<u8>, NoiseError> {
        let Some(key) = self.key else {
            return Ok(plaintext.to_vec());
        };
        if self.n == u64::MAX {
            return Err(NoiseError::NonceExhausted);
        }
        let cipher = ChaCha20Poly1305::new(Key::from_slice(&key));
        let out = cipher
            .encrypt(
                Nonce::from_slice(&nonce_bytes(self.n)),
                Payload {
                    msg: plaintext,
                    aad: ad,
                },
            )
            .map_err(|_| NoiseError::Decryption)?;
        self.n += 1;
        Ok(out)
    }

    /// The nonce only advances on success, so a forged or corrupted frame cannot desynchronise the session.
    fn decrypt_with_ad(&mut self, ad: &[u8], ciphertext: &[u8]) -> Result<Vec<u8>, NoiseError> {
        let Some(key) = self.key else {
            return Ok(ciphertext.to_vec());
        };
        if self.n == u64::MAX {
            return Err(NoiseError::NonceExhausted);
        }
        if ciphertext.len() < TAG_LEN {
            return Err(NoiseError::InvalidMessage);
        }
        let cipher = ChaCha20Poly1305::new(Key::from_slice(&key));
        let out = cipher
            .decrypt(
                Nonce::from_slice(&nonce_bytes(self.n)),
                Payload {
                    msg: ciphertext,
                    aad: ad,
                },
            )
            .map_err(|_| NoiseError::Decryption)?;
        self.n += 1;
        Ok(out)
    }
}

/// Chaining key, transcript hash and the handshake cipher (spec section 5.2).
#[derive(Zeroize, ZeroizeOnDrop)]
struct SymmetricState {
    ck: [u8; 32],
    h: [u8; 32],
    cs: CipherState,
}

impl SymmetricState {
    fn new(protocol_name: &str) -> Self {
        let name = protocol_name.as_bytes();
        let h = if name.len() <= 32 {
            let mut padded = [0u8; 32];
            padded[..name.len()].copy_from_slice(name);
            padded
        } else {
            sha256(&[name])
        };
        Self {
            ck: h,
            h,
            cs: CipherState::empty(),
        }
    }

    fn mix_hash(&mut self, data: &[u8]) {
        self.h = sha256(&[&self.h, data]);
    }

    fn mix_key(&mut self, ikm: &[u8]) {
        let (ck, temp_k) = hkdf2(&self.ck, ikm);
        self.ck = ck;
        self.cs.set_key(temp_k);
    }

    fn encrypt_and_hash(&mut self, plaintext: &[u8]) -> Result<Vec<u8>, NoiseError> {
        let ct = self.cs.encrypt_with_ad(&self.h, plaintext)?;
        self.mix_hash(&ct);
        Ok(ct)
    }

    fn decrypt_and_hash(&mut self, ciphertext: &[u8]) -> Result<Vec<u8>, NoiseError> {
        let pt = self.cs.decrypt_with_ad(&self.h, ciphertext)?;
        self.mix_hash(ciphertext);
        Ok(pt)
    }

    /// Splits into the two transport directions: first is initiator-to-responder.
    fn split(&self) -> (CipherState, CipherState) {
        let (k1, k2) = hkdf2(&self.ck, &[]);
        (CipherState::with_key(k1), CipherState::with_key(k2))
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Stage {
    Start,
    AwaitingMessage2,
    AwaitingMessage1Done,
    Complete,
}

/// The Noise_IK handshake. Initiator: `write_message1` then `read_message2`. Responder: `read_message1` then
/// `write_message2`.
pub struct Handshake {
    role: Role,
    symmetric: SymmetricState,
    s: StaticSecret,
    s_pub: [u8; 32],
    e: Option<StaticSecret>,
    rs: Option<[u8; 32]>,
    re: Option<[u8; 32]>,
    stage: Stage,
}

impl std::fmt::Debug for Handshake {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Handshake")
            .field("role", &self.role)
            .field("stage", &self.stage)
            .finish_non_exhaustive()
    }
}

impl Drop for Handshake {
    fn drop(&mut self) {
        self.s.zeroize();
        if let Some(e) = self.e.as_mut() {
            e.zeroize();
        }
    }
}

impl Handshake {
    /// `remote_static` is the responder's static public key, known from pairing.
    pub fn initiator(local: &StaticKeypair, remote_static: [u8; 32], prologue: &[u8]) -> Self {
        let mut symmetric = SymmetricState::new(PROTOCOL_NAME);
        symmetric.mix_hash(prologue);
        symmetric.mix_hash(&remote_static);
        Self::new(Role::Initiator, symmetric, local, Some(remote_static))
    }

    pub fn responder(local: &StaticKeypair, prologue: &[u8]) -> Self {
        let mut symmetric = SymmetricState::new(PROTOCOL_NAME);
        symmetric.mix_hash(prologue);
        symmetric.mix_hash(&local.public_bytes());
        Self::new(Role::Responder, symmetric, local, None)
    }

    fn new(
        role: Role,
        symmetric: SymmetricState,
        local: &StaticKeypair,
        rs: Option<[u8; 32]>,
    ) -> Self {
        Self {
            role,
            symmetric,
            s: StaticSecret::from(local.secret_bytes()),
            s_pub: local.public_bytes(),
            e: None,
            rs,
            re: None,
            stage: Stage::Start,
        }
    }

    pub fn role(&self) -> Role {
        self.role
    }

    /// The peer's static key: known up front to the initiator, learned from message 1 by the responder.
    pub fn remote_static(&self) -> Option<[u8; 32]> {
        self.rs
    }

    /// `-> e, es, s, ss`. `ephemeral` is a fresh random 32-byte secret from the caller.
    pub fn write_message1(
        &mut self,
        payload: &[u8],
        ephemeral: [u8; 32],
    ) -> Result<Vec<u8>, NoiseError> {
        if self.role != Role::Initiator || self.stage != Stage::Start {
            return Err(NoiseError::WrongState);
        }
        let rs = self.rs.ok_or(NoiseError::WrongState)?;
        let e = StaticSecret::from(ephemeral);
        let e_pub = PublicKey::from(&e).to_bytes();

        let mut out = Vec::with_capacity(DH_LEN + ENCRYPTED_STATIC_LEN + payload.len() + TAG_LEN);
        out.extend_from_slice(&e_pub);
        self.symmetric.mix_hash(&e_pub);

        self.symmetric.mix_key(&dh(&e, &rs)?);
        out.extend_from_slice(&self.symmetric.encrypt_and_hash(&self.s_pub)?);

        self.symmetric.mix_key(&dh(&self.s, &rs)?);
        out.extend_from_slice(&self.symmetric.encrypt_and_hash(payload)?);

        self.e = Some(e);
        self.stage = Stage::AwaitingMessage2;
        Ok(out)
    }

    /// Consumes message 1; returns the decrypted payload. The initiator's static key is then in `remote_static`.
    pub fn read_message1(&mut self, message: &[u8]) -> Result<Vec<u8>, NoiseError> {
        if self.role != Role::Responder || self.stage != Stage::Start {
            return Err(NoiseError::WrongState);
        }
        if message.len() < DH_LEN + ENCRYPTED_STATIC_LEN + TAG_LEN {
            return Err(NoiseError::InvalidMessage);
        }
        let re: [u8; 32] = message[..DH_LEN].try_into().expect("length checked");
        self.symmetric.mix_hash(&re);

        self.symmetric.mix_key(&dh(&self.s, &re)?);
        let static_end = DH_LEN + ENCRYPTED_STATIC_LEN;
        let rs_bytes = self
            .symmetric
            .decrypt_and_hash(&message[DH_LEN..static_end])?;
        let rs: [u8; 32] = rs_bytes
            .try_into()
            .map_err(|_| NoiseError::InvalidMessage)?;

        self.symmetric.mix_key(&dh(&self.s, &rs)?);
        let payload = self.symmetric.decrypt_and_hash(&message[static_end..])?;

        self.re = Some(re);
        self.rs = Some(rs);
        self.stage = Stage::AwaitingMessage1Done;
        Ok(payload)
    }

    /// `<- e, ee, se`; completes the responder side.
    pub fn write_message2(
        &mut self,
        payload: &[u8],
        ephemeral: [u8; 32],
    ) -> Result<(Vec<u8>, Transport), NoiseError> {
        if self.role != Role::Responder || self.stage != Stage::AwaitingMessage1Done {
            return Err(NoiseError::WrongState);
        }
        let (re, rs) = (
            self.re.ok_or(NoiseError::WrongState)?,
            self.rs.ok_or(NoiseError::WrongState)?,
        );
        let e = StaticSecret::from(ephemeral);
        let e_pub = PublicKey::from(&e).to_bytes();

        let mut out = Vec::with_capacity(DH_LEN + payload.len() + TAG_LEN);
        out.extend_from_slice(&e_pub);
        self.symmetric.mix_hash(&e_pub);

        self.symmetric.mix_key(&dh(&e, &re)?);
        self.symmetric.mix_key(&dh(&e, &rs)?);
        out.extend_from_slice(&self.symmetric.encrypt_and_hash(payload)?);

        let (c1, c2) = self.symmetric.split();
        self.e = Some(e);
        self.stage = Stage::Complete;
        Ok((
            out,
            Transport {
                send: c2,
                recv: c1,
                handshake_hash: self.symmetric.h,
            },
        ))
    }

    /// Consumes message 2; returns its payload and the transport ciphers.
    pub fn read_message2(&mut self, message: &[u8]) -> Result<(Vec<u8>, Transport), NoiseError> {
        if self.role != Role::Initiator || self.stage != Stage::AwaitingMessage2 {
            return Err(NoiseError::WrongState);
        }
        if message.len() < DH_LEN + TAG_LEN {
            return Err(NoiseError::InvalidMessage);
        }
        let e = self.e.as_ref().ok_or(NoiseError::WrongState)?;
        let re: [u8; 32] = message[..DH_LEN].try_into().expect("length checked");
        self.symmetric.mix_hash(&re);

        let ee = dh(e, &re)?;
        let se = dh(&self.s, &re)?;
        self.symmetric.mix_key(&ee);
        self.symmetric.mix_key(&se);
        let payload = self.symmetric.decrypt_and_hash(&message[DH_LEN..])?;

        let (c1, c2) = self.symmetric.split();
        self.re = Some(re);
        self.stage = Stage::Complete;
        Ok((
            payload,
            Transport {
                send: c1,
                recv: c2,
                handshake_hash: self.symmetric.h,
            },
        ))
    }
}

/// The two post-handshake cipher states for one session.
#[derive(ZeroizeOnDrop)]
pub struct Transport {
    send: CipherState,
    recv: CipherState,
    #[zeroize(skip)]
    handshake_hash: [u8; 32],
}

impl std::fmt::Debug for Transport {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Transport").finish_non_exhaustive()
    }
}

impl Transport {
    pub fn encrypt(&mut self, plaintext: &[u8]) -> Result<Vec<u8>, NoiseError> {
        self.send.encrypt_with_ad(&[], plaintext)
    }

    /// Does not advance the receive nonce on failure.
    pub fn decrypt(&mut self, ciphertext: &[u8]) -> Result<Vec<u8>, NoiseError> {
        self.recv.decrypt_with_ad(&[], ciphertext)
    }

    /// The final transcript hash, a unique session identifier usable for channel binding.
    pub fn handshake_hash(&self) -> [u8; 32] {
        self.handshake_hash
    }

    pub fn messages_sent(&self) -> u64 {
        self.send.n
    }

    pub fn messages_received(&self) -> u64 {
        self.recv.n
    }
}
