package dev.vmd1.gossip.crypto

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.assertFalse
import org.junit.Test
import java.io.File

class NoiseSessionTest {

    @Test
    fun `full IK handshake between two in-process instances completes and derives matching transport keys`() {
        val initiatorStatic = X25519Utils.generateKeyPair()
        val responderStatic = X25519Utils.generateKeyPair()

        val initiator = NoiseSession(NoiseRole.INITIATOR, initiatorStatic, responderStatic.publicKey)
        val responder = NoiseSession(NoiseRole.RESPONDER, responderStatic, null)

        val helloPayload = "hello-from-initiator".toByteArray()
        val message1 = initiator.writeMessage1(helloPayload)

        val result1 = responder.readMessage1(message1)
        assertArrayEquals(helloPayload, result1.payload)
        assertArrayEquals(initiatorStatic.publicKey, result1.remoteStaticPublicKey)

        val ackPayload = "hello-from-responder".toByteArray()
        val message2 = responder.writeMessage2(ackPayload)
        assertTrue(responder.isComplete)

        val decodedAck = initiator.readMessage2(message2)
        assertArrayEquals(ackPayload, decodedAck)
        assertTrue(initiator.isComplete)

        // Post-handshake transport encryption: initiator -> responder.
        val appMessage = "{\"type\":\"presence.online\"}".toByteArray()
        val ciphertext = initiator.encryptTransportMessage(appMessage)
        val plaintext = responder.decryptTransportMessage(ciphertext)
        assertArrayEquals(appMessage, plaintext)

        // And the other direction: responder -> initiator.
        val replyMessage = "{\"type\":\"presence.heartbeat\"}".toByteArray()
        val replyCiphertext = responder.encryptTransportMessage(replyMessage)
        val replyPlaintext = initiator.decryptTransportMessage(replyCiphertext)
        assertArrayEquals(replyMessage, replyPlaintext)
    }

    @Test(expected = NoiseHandshakeException::class)
    fun `decrypting a tampered ciphertext fails authentication`() {
        val initiatorStatic = X25519Utils.generateKeyPair()
        val responderStatic = X25519Utils.generateKeyPair()

        val initiator = NoiseSession(NoiseRole.INITIATOR, initiatorStatic, responderStatic.publicKey)
        val responder = NoiseSession(NoiseRole.RESPONDER, responderStatic, null)

        val message1 = initiator.writeMessage1(ByteArray(0))
        responder.readMessage1(message1)
        val message2 = responder.writeMessage2(ByteArray(0))
        initiator.readMessage2(message2)

        val ciphertext = initiator.encryptTransportMessage("secret".toByteArray())
        ciphertext[0] = (ciphertext[0].toInt() xor 0xFF).toByte() // flip every bit in the first byte
        responder.decryptTransportMessage(ciphertext)
    }

    @Test
    fun `handshake fails when initiator has the wrong responder static key`() {
        val initiatorStatic = X25519Utils.generateKeyPair()
        val responderStatic = X25519Utils.generateKeyPair()
        val wrongStatic = X25519Utils.generateKeyPair()

        val initiator = NoiseSession(NoiseRole.INITIATOR, initiatorStatic, wrongStatic.publicKey)
        val responder = NoiseSession(NoiseRole.RESPONDER, responderStatic, null)

        val message1 = initiator.writeMessage1(ByteArray(0))

        var threw = false
        try {
            responder.readMessage1(message1)
        } catch (e: NoiseHandshakeException) {
            threw = true
        }
        assertTrue("Handshake using the wrong static key should fail authentication", threw)
        assertFalse(responder.isComplete)
    }

    private fun hex(s: String) = ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
    private fun hex(b: ByteArray) = b.joinToString("") { "%02x".format(it) }

    private fun noiseVectors(): JsonObject {
        var dir: File? = File("").absoluteFile
        while (dir != null && !File(dir, "schema/noise-ik-vectors.json").exists()) dir = dir.parentFile
        return Json.parseToJsonElement(File(checkNotNull(dir), "schema/noise-ik-vectors.json").readText()).jsonObject
    }

    /** The shared conformance vectors (`schema/noise-ik-vectors.json`), generated by an implementation independent of
     *  both apps. The Swift twin is `NoiseSessionTests.testSharedNoiseVectors`; the Rust core checks the same file. */
    @Test
    fun `shared noise vectors match`() {
        for (caseElement in noiseVectors()["cases"]!!.jsonArray) {
            val c = caseElement.jsonObject
            fun str(key: String) = c[key]!!.jsonPrimitive.content
            val name = str("name")
            val initiatorStatic = X25519Utils.keyPairFromPrivate(hex(str("initiatorStaticSecretHex")))
            val responderStatic = X25519Utils.keyPairFromPrivate(hex(str("responderStaticSecretHex")))
            val initiator = NoiseSession(NoiseRole.INITIATOR, initiatorStatic, responderStatic.publicKey)
            val responder = NoiseSession(NoiseRole.RESPONDER, responderStatic, null)

            val message1 = initiator.writeMessage1(hex(str("message1PayloadHex")), X25519Utils.keyPairFromPrivate(hex(str("initiatorEphemeralSecretHex"))))
            assertEquals("$name: message 1", str("message1Hex"), hex(message1))
            assertArrayEquals(name, hex(str("message1PayloadHex")), responder.readMessage1(message1).payload)
            val message2 = responder.writeMessage2(hex(str("message2PayloadHex")), X25519Utils.keyPairFromPrivate(hex(str("responderEphemeralSecretHex"))))
            assertEquals("$name: message 2", str("message2Hex"), hex(message2))
            assertArrayEquals(name, hex(str("message2PayloadHex")), initiator.readMessage2(message2))

            c["transport"]!!.jsonArray.forEachIndexed { n, stepElement ->
                val step = stepElement.jsonObject
                val (sender, receiver) = if (step["direction"]!!.jsonPrimitive.content == "i2r") initiator to responder else responder to initiator
                val plaintext = hex(step["plaintextHex"]!!.jsonPrimitive.content)
                val ciphertext = sender.encryptTransportMessage(plaintext)
                assertEquals("$name: transport message $n", step["ciphertextHex"]!!.jsonPrimitive.content, hex(ciphertext))
                assertArrayEquals("$name: transport message $n", plaintext, receiver.decryptTransportMessage(ciphertext))
            }
        }
    }
}
