/**
 * Generates schema/conformance/relay-vectors.json: fixed conformance vectors
 * for the relay's join/topic/route-tag/PoW cryptography. Run with
 *   npm run gen-vectors
 * Output is fully deterministic (Ed25519 signatures are deterministic and the
 * PoW solution is the smallest counter).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  b64,
  ed25519PublicFromSeed,
  ed25519Sign,
  joinProof,
  joinSigningInput,
  powDigest,
  publicKeyHash,
  routeTag,
  sha256,
  solvePow,
  topicAuthKey,
  topicId,
  topicVerifier,
  u64be,
  leadingZeroBits,
} from "../src/crypto.js";

const seq = (start: number, n = 32) => Buffer.from(Array.from({ length: n }, (_, i) => (start + i) & 0xff));

export const VECTORS_PATH = fileURLToPath(new URL("../../schema/conformance/relay-vectors.json", import.meta.url));

export function buildVectors() {
  const relayOrigin = "wss://relay.example.test";
  const topicSecret = seq(0x40);
  const nonce = seq(0x80);
  const powBits = 16;
  const seedA = seq(0x01);
  const seedB = seq(0x21);

  const device = (name: string, seed: Buffer) => {
    const pub = ed25519PublicFromSeed(seed);
    return { name, seedHex: seed.toString("hex"), publicKey: b64(pub), publicKeyHashHex: publicKeyHash(pub).toString("hex") };
  };
  const devA = device("A", seedA);
  const devB = device("B", seedB);
  const pubA = ed25519PublicFromSeed(seedA);
  const pubB = ed25519PublicFromSeed(seedB);

  const epochs = [1n, 0x0102030405060708n].map((epoch) => {
    const tid = topicId(topicSecret, epoch);
    const ak = topicAuthKey(topicSecret, epoch);
    return {
      epoch: epoch.toString(),
      epochU64beHex: u64be(epoch).toString("hex"),
      topicIdHex: tid.toString("hex"),
      topicAuthKeyHex: ak.toString("hex"),
      verifierHex: topicVerifier(ak).toString("hex"),
      routeTagAHex: routeTag(tid, publicKeyHash(pubA)).toString("hex"),
      routeTagBHex: routeTag(tid, publicKeyHash(pubB)).toString("hex"),
    };
  });

  // Join for device A on epoch 1.
  const tid = topicId(topicSecret, 1n);
  const verifier = topicVerifier(topicAuthKey(topicSecret, 1n));
  const signingInput = joinSigningInput(relayOrigin, nonce, tid);
  const sig = ed25519Sign(seedA, signingInput);
  const proof = joinProof(verifier, nonce);
  const keyHash = publicKeyHash(pubA);
  const pow = solvePow(keyHash, nonce, powBits);
  const digest = powDigest(keyHash, nonce, pow);

  const frameDst = Buffer.from(epochs[0]!.routeTagBHex, "hex");
  const frameClaimedSrc = Buffer.from("deadbeefdeadbeef", "hex");
  const frameSrc = Buffer.from(epochs[0]!.routeTagAHex, "hex");
  const payload = Buffer.from("opaque noise ciphertext bytes", "utf8");

  return {
    description:
      "Relay conformance vectors (docs/plans/relay.md). All *Hex fields are lowercase hex; every binary field inside a JSON message is standard padded base64. Generated by relay/scripts/gen-vectors.ts; verified by relay/test/vectors.test.ts.",
    notes: {
      publicKeyHash: "SHA-256(ed25519 public key, 32 bytes)",
      topicId: "HMAC-SHA256(key=topicSecret, msg=utf8('gossip-topic') || u64be(epoch))",
      topicAuthKey: "HMAC-SHA256(key=topicSecret, msg=utf8('gossip-topic-auth') || u64be(epoch))",
      verifier: "SHA-256(topicAuthKey); registered by the first joiner, sent in every join",
      routeTag: "SHA-256(topicId || publicKeyHash)[0..8]",
      sigInput: "utf8('gossip-relay-join-v1\\n') || utf8(relayOrigin) || 0x0A || nonce(32) || topicId(32); sig = Ed25519 over that",
      proof:
        "HMAC-SHA256(key=verifier(32), msg=nonce(32)). The relay stores only SHA-256(topicAuthKey), so it cannot verify an HMAC keyed by topicAuthKey itself; the proof is keyed by the verifier the join carries.",
      pow: "pow = 8 bytes (u64be counter); valid iff SHA-256(utf8('gossip-relay-pow-v1') || publicKeyHash || nonce || pow) has >= powBits leading zero bits. Required only when the relay has not seen the key hash before.",
      frame: "binary WebSocket message: dstTag(8) || srcTag(8) || payload. Relay overwrites srcTag with the sender's route tag.",
    },
    relayOrigin,
    topicSecretHex: topicSecret.toString("hex"),
    devices: [devA, devB],
    topics: epochs,
    join: {
      device: "A",
      epoch: "1",
      nonceHex: nonce.toString("hex"),
      powBits,
      signingInputHex: signingInput.toString("hex"),
      sigHex: sig.toString("hex"),
      proofHex: proof.toString("hex"),
      powCounter: pow.readBigUInt64BE().toString(),
      powHex: pow.toString("hex"),
      powDigestHex: digest.toString("hex"),
      powLeadingZeroBits: leadingZeroBits(digest),
      challengeMessage: { type: "relay.challenge", nonce: b64(nonce), powBits },
      joinMessage: {
        type: "relay.join",
        publicKey: b64(pubA),
        topicId: b64(tid),
        sig: b64(sig),
        verifier: b64(verifier),
        proof: b64(proof),
        version: "2.0",
        pow: b64(pow),
      },
    },
    frame: {
      dstTagHex: frameDst.toString("hex"),
      claimedSrcTagHex: frameClaimedSrc.toString("hex"),
      payloadHex: payload.toString("hex"),
      sentFrameHex: Buffer.concat([frameDst, frameClaimedSrc, payload]).toString("hex"),
      deliveredFrameHex: Buffer.concat([frameDst, frameSrc, payload]).toString("hex"),
    },
    sha256OfEmptyHex: sha256(Buffer.alloc(0)).toString("hex"),
  };
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  writeFileSync(VECTORS_PATH, JSON.stringify(buildVectors(), null, 2) + "\n");
  console.log(`wrote ${VECTORS_PATH}`);
}
